#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: one stage per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Delivery Factory: identity, model and the pause switch"

# ── 1 ───────────────────────────────────────────────────────────────────────
stage "The model the factory runs on"
say "The factory pins one model, so a run can never quietly pick something else."
note "The model id is a repository *variable* (FACTORY_MODEL); the key is a *secret*."
step "Press Enter to accept the pinned model, or type another provider/model id."
# Seeded first: `ask` defaults to the value already in .env, and that is how
# "press Enter" keeps the model this repo actually runs on.
write_env FACTORY_MODEL "${FACTORY_MODEL:-opencode-go/space-bunny-free}"
ask FACTORY_MODEL "Model id (provider/model):"
if [ -z "$FACTORY_MODEL" ]; then
  warn "no model given; the workflows will pass an empty model and the action will fail loudly"
fi
step "Create a provider API key for that model."
step "The secret must be named for the env the provider reads, because the workflows"
step "  pass ANTHROPIC_API_KEY / OPENAI_API_KEY / OPENCODE_API_KEY through."
note "For opencode-go / opencode Zen that env is OPENCODE_API_KEY."
ask KEY_ENV "Which env does your provider read? (default OPENCODE_API_KEY):"
KEY_ENV="${KEY_ENV:-OPENCODE_API_KEY}"
ask_secret PROVIDER_KEY "Provider API key:"
set_var FACTORY_MODEL "$FACTORY_MODEL"
if [ -n "$PROVIDER_KEY" ] && [ -n "$KEY_ENV" ]; then
  printf '%s' "$PROVIDER_KEY" | gh secret set "$KEY_ENV" >/dev/null 2>&1 \
    && note "set GitHub secret $KEY_ENV" \
    || warn "could not set $KEY_ENV — set it manually: gh secret set $KEY_ENV"
elif [ -n "$KEY_ENV" ]; then
  warn "no key captured — set it manually: gh secret set $KEY_ENV"
fi

# Signs a short-lived JWT with the App's own key and asks GitHub who it is.
#
# This is the difference between "the field was filled in" and "the identity
# works". It catches a wrong App ID, a key belonging to a different App, and the
# failure that actually bit us: an App that was created but never installed,
# which no amount of correct configuration can fix.
verify_app_identity() {
  local app_id="${FACTORY_APP_ID:-}"
  if [[ -z "$app_id" ]]; then
    warn "no App ID to verify against"
    return 0
  fi
  if ! command -v openssl >/dev/null 2>&1 || ! command -v python3 >/dev/null 2>&1; then
    warn "openssl or python3 missing — skipping the identity check"
    return 0
  fi

  local jwt
  jwt=$(FACTORY_APP_ID="$app_id" FACTORY_PEM="$PEM_PATH" python3 -c '
import base64, json, os, subprocess, time
b64 = lambda b: base64.urlsafe_b64encode(b).rstrip(b"=").decode()
now = int(time.time())
head = b64(json.dumps({"alg": "RS256", "typ": "JWT"}, separators=(",", ":")).encode())
body = b64(json.dumps({"iat": now - 60, "exp": now + 540,
                       "iss": os.environ["FACTORY_APP_ID"]}, separators=(",", ":")).encode())
sig = subprocess.run(["openssl", "dgst", "-sha256", "-sign", os.environ["FACTORY_PEM"], "-binary"],
                     input=f"{head}.{body}".encode(), capture_output=True).stdout
print(f"{head}.{body}.{b64(sig)}", end="")
' 2>/dev/null || true)
  if [[ -z "$jwt" ]]; then
    warn "could not sign a JWT locally — skipping the identity check"
    return 0
  fi

  local slug count
  slug=$(gh api /app --jq '.slug' -H "Authorization: Bearer $jwt" 2>/dev/null)
  if [[ -z "$slug" ]]; then
    warn "GitHub rejected the identity: this App ID and this key are not a pair."
    warn "  check General → App ID on the same App the .pem came from"
    return 0
  fi
  note "identity verified: $slug"

  count=$(gh api /app/installations --jq '.installations | length' -H "Authorization: Bearer $jwt" 2>/dev/null)
  if [[ "$count" == "0" ]]; then
    warn "the App is NOT installed on any account, so CI cannot mint a token yet."
    warn "  open https://github.com/settings/apps/$slug → Install App → Convocados"
  else
    note "installed on $count account(s)"
  fi
}

# ── 2 ───────────────────────────────────────────────────────────────────────
stage "Create the convoyados-factory App"
say "Our own App, not the opencode App: ADR 0048 keeps the blast radius ours to audit."
warn "GitHub never lets a PR author approve their own PR, so the factory must NOT"
warn "push as @Cabeda — it would permanently block its own Changes."
open_url "https://github.com/settings/apps/new"
# These are printed one per line, with no bullet, so a copy lands clean. The
# previous version wrapped them inside a numbered step, and GitHub rejected the
# paste with "must be a valid URL".
copy_value() { printf '      %s\n' "$1"; }

step "App name — copy exactly:"
copy_value "convocados-factory"
step "Homepage URL — copy exactly, nothing else on the line:"
copy_value "https://github.com/Cabeda/Convocados"
step "Callback URL — copy exactly, nothing else on the line:"
copy_value "https://github.com/Cabeda/Convocados"
step "Webhook URL is mandatory in GitHub's form. Put the same value: it is inert,"
step "  because no events are subscribed and the factory polls instead."
copy_value "https://github.com/Cabeda/Convocados"
step "Repository permissions: Contents = Read & write, Pull requests = Read & write,"
step "  Issues = Read & write, Metadata = Read-only. Everything else = No access."
warn "Do NOT grant: Workflows, Administration, Secrets, Pages, or Merge queues."
step "Where is the app installed? → Only on selected repositories → type_convocados"
pause "Press Enter once the App exists and is installed on Cabeda/Convocados."

# ── 3 ───────────────────────────────────────────────────────────────────────
stage "App id and private key"
open_url "https://github.com/settings/apps"
step "Open your App → General → 'App ID' near the top of the page."
note "GitHub issues two shapes and both are valid: a numeric id (5120869) for"
note "  older Apps, and a string id (Iv23liiCQiPKY7puYnzQ) for current ones."
ask FACTORY_APP_ID "App ID:"
if [[ -z "$FACTORY_APP_ID" ]]; then
  warn "no App ID given — the previous value is left alone"
else
  set_var FACTORY_APP_ID "$FACTORY_APP_ID"
fi

step "Private keys → 'Generate a private key'. GitHub downloads a .pem (and emails a link)."
note "Do NOT paste the PEM into a prompt. It is many lines, a one-line prompt reads"
note "  only the first of them, and the rest is silently eaten by the next question."
step "Leave the file where GitHub put it, then type its path here."
ask PEM_PATH "Path to the .pem file (or just its name if it is in ~/Downloads):"
[[ "$PEM_PATH" != /* ]] && PEM_PATH="$HOME/Downloads/$PEM_PATH"
if [ -f "$PEM_PATH" ] && grep -q "BEGIN" "$PEM_PATH" && grep -q "PRIVATE KEY" "$PEM_PATH"; then
  # The whole file, exactly as generated: BEGIN/END lines included.
  if gh secret set FACTORY_APP_KEY < "$PEM_PATH" >/dev/null 2>&1; then
    note "set GitHub secret FACTORY_APP_KEY from $PEM_PATH"
  else
    warn "could not set FACTORY_APP_KEY — set it manually:"
    warn "  gh secret set FACTORY_APP_KEY < $PEM_PATH"
  fi
  verify_app_identity
  rm -f "$PEM_PATH" && note "removed the downloaded key file (the secret holds it now)"
else
  warn "no usable PEM at '$PEM_PATH' — nothing set."
  warn "check the path, then: gh secret set FACTORY_APP_KEY < /full/path/to/key.pem"
fi

# ── 4 ───────────────────────────────────────────────────────────────────────
stage "The pause switch, then the first run"
say "FACTORY_PAUSED is the only off switch, and no machine may set or clear it."
set_var FACTORY_PAUSED "true"
note "Left as true on purpose. Flip it to false when you want it live:"
note "  gh variable set FACTORY_PAUSED --body false"
step "Then dispatch one manual run and watch it: gh workflow run factory-issue.yml"
step "  -f issue=<number of an Issue labelled ready-for-agent>"
say "Nothing is automatic until an Issue carries the label, and only you apply it."

finish
