packages:
  - "."

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@eslint-react/ast@5.17.3'
  - '@eslint-react/core@5.17.3'
  - '@eslint-react/eslint-plugin@5.17.3'
  - '@eslint-react/eslint@5.17.3'
  - '@eslint-react/jsx@5.17.3'
  - '@eslint-react/shared@5.17.3'
  - '@eslint-react/var@5.17.3'
  - eslint-plugin-react-dom@5.17.3
  - eslint-plugin-react-jsx@5.17.3
  - eslint-plugin-react-naming-convention@5.17.3
  - eslint-plugin-react-rsc@5.17.3
  - eslint-plugin-react-web-api@5.17.3
  - eslint-plugin-react-x@5.17.3
overrides:
  basic-ftp@<=5.2.2: '>=5.3.0'
  basic-ftp@<=5.3.0: '>=5.3.1'
  better-auth@<1.6.2: '>=1.6.2'
  brace-expansion@>=5.0.0 <5.0.6: '>=5.0.6'
  devalue@>=5.6.3 <=5.8.0: '>=5.8.1'
  effect@<3.20.0: '>=3.20.0'
  ip-address@<=10.1.0: '>=10.1.1'
  kysely@>=0.26.0 <0.28.17: '>=0.28.17'
  path-to-regexp@<0.1.13: '>=0.1.13'
  qs@>=6.11.1 <=6.15.1: '>=6.15.2'
  tmp@<0.2.6: '>=0.2.6'
  tmp@<=0.2.3: '>=0.2.4'
  uuid@<11.1.1: '>=11.1.1'
  ws@>=8.0.0 <8.20.1: '>=8.20.1'
