app = "convocados-scheduler"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_URL = "https://convocados.fly.dev"
  CONCURRENCY = "3"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
